name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        ghc: [804, 806, 808, 810]

    runs-on: ubuntu-latest
    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml

    steps:
    - uses: actions/checkout@v2
    - name: Setup Stack
      uses: mstksg/setup-stack@v2

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-local
      with:
        path: '**/.stack-work'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        stack update
        stack build --only-dependencies --test --bench --no-run-tests --no-run-benchmarks
    - name: Build
      run: stack build --test --bench --no-run-tests --no-run-benchmarks
    - name: Run tests
      run: stack test
