name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        ghc: ["8.6.5", "8.8.4", "8.10.3"]
        falliable: [false]
        include:
        - ghc: "9.0.1"
          falliable: true
      fail-fast: false
    continue-on-error: ${{ matrix.falliable }}
    runs-on: ubuntu-latest
    env:
      STACK_YAML: stack-${{ matrix.ghc }}.yaml

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack-local
      with:
        path: '**/.stack-work'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.ghc }}
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Setup Stack
      uses: haskell/actions/setup@v1.1.7
      with:
        enable-stack: true
        stack-no-global: true

    - name: Install dependencies
      run: |
        stack build --only-dependencies --test --bench --no-run-tests --no-run-benchmarks
    - name: Build
      run: stack build --test --bench --no-run-tests --no-run-benchmarks
    - name: Run tests
      run: stack test
